### ISSUE TITLE
`zt` goes all the way up and `zb` goes all the way to down

### ISSUE THREAD

**Issue by numToStr** [karb94/neoscroll.nvim#11]
First of all thanks for this lovely plugin ❤️ . This plugin is awesome.

Back to the issue, So, When you press `zt`, the cursor goes all the way to the top, and `zb` goes all the way down but `zz` works great. This is not the expected behavior of the vanilla commands.

https://user-images.githubusercontent.com/24727447/113581275-94017c80-9644-11eb-895e-a24aada4b64e.mp4

**Comment by karb94** [comment]
Do you have `scrolloff` set to 999 by any chance?

**Comment by numToStr** [comment]
No, my `scrolloff` is `8`. In fact, other commands i.e. `<C-u>`, `<C-d>` are working just fine.

**Comment by karb94** [comment]
I can't reproduce. It's weird because there is not much going on in the wrapper functions for `zt`/`zb`. The lines to scroll are calculated based on the cursor position in the window (which I assume is fine given that `<C-u>` and `<C-d>` work for you) and the local `scrolloff` value. Can you please double check that if you run

```lua
:lua print(vim.wo.scrolloff)
```

you get a value of 8?

**Comment by numToStr** [comment]
So, I think there is something wrong. When I run `:lua print(vim.o.scrolloff)` I get a value of `0` but when I `:lua print(vim.wo.scrolloff)` i get this `1.4065270751731e+14`. 🤯

**Comment by numToStr** [comment]
After `vim.wo.scrolloff=8` everything works fine.

@karb94 Your plugin is working fine. I think you can close this issue.

**Comment by karb94** [comment]
I see... local `scrolloff` looks kind of broken to me. When it is not set it just display a garbage value instead of the global one. I don't know if this is the expected behaviour (I hope not). I'll open an issue about this.

Because of this it is impossible for me to tell if you have set a local `scrolloff` value different from the global one. I added a temporary fix (930f823) by checking that the local `scrolloff` value is lower than the window height otherwise I use the global value.

Let me know if this fix doesn't work for you.

**Comment by karb94** [comment]
Indeed, this appears to be a bug: https://github.com/neovim/neovim/issues/13964

I'll keep track of it and update the code when it gets resolved.
