### ISSUE TITLE
petertriho/nvim-scrollbar goes mad when scrolling

### ISSUE THREAD

**Issue by ssastrukovs** [karb94/neoscroll.nvim#114]
petertriho/nvim-scrollbar scrollbar minimap on the side does seem to scroll with the window. 

Maybe there could be some kind of integration in mind?

Here's a video example, I'm doing C-u and C-d back and forth:
[neoscroll_scrollbar.webm](https://github.com/user-attachments/assets/4575f5df-094d-4c93-b199-93958e6e8edb)

**Comment by karb94** [comment]
This is likely because nvim-scrollbar uses the `WinScrolled` event to update the scrollbar and Neoscroll disables that event by default for performance reasons. Try `ignored_events = {}` in your config but be warned that it will impact performance.

In my opinion, a better solution would be to get rid of the scrollbar before the scroll with the `pre_hook` option and activate it again after the scroll with the `post_hook` option. This way you won't get a scrollbar while scrolling but you will keep the scroll smooth. I am not familiar with the plugin so I cannot tell you exactly how to do it.

**Comment by ssastrukovs** [comment]
Putting ```WinScrolled``` in ```ignored_events``` did work, thank you.

A "hide" and "show" pre and post hooks for scrollbar also work, thank you for the thought.    
I guess that could be an option too on lower-end PCs. In my case (Ryzen 7 5700G CPU), CPU usage goes from 7-11% with disabled ```WinScrolled``` event to 4-6% with pre- and post-hooks of disabling the scrollbar. 
Don't know about the GPU, I guess WezTerm that I'm on might use it too somewhere around the pipeline, but there's that.   

For those wondering how to do hide and show hooks, something like this works:
```lua
pre_hook = function()
  local scrollbar_util = require 'scrollbar.utils'
  scrollbar_util.hide()
end,
post_hook = function()
  local scrollbar_util = require 'scrollbar.utils'
  scrollbar_util.show()
end,
```
