### ISSUE TITLE
Change time_step "Globally"

### ISSUE THREAD

**Issue by kishikaisei** [karb94/neoscroll.nvim#17]
I couldn't find it in the documentation, but is there a way to change the time_step for all the commands, for me the default is quite slow. If not, something maybe like this could be nice:
```
require('neoscroll').setup({
    mappings = {'<C-u>', '<C-d>', '<C-b>',
        '<C-f>', '<C-y>', '<C-e>', 'zt', 'zz', 'zb'},
    hide_cursor = true,
    stop_eof = true,
    respect_scrolloff = false,
    cursor_scrolls_alone = true,
    time_step = 5  -- This option?
})

**Comment by karb94** [comment]
I'm not going to introduce options that can be replicated with a bit of code. Also using the same `time_step` for all the mappings would feel ackward as some motions are way shorter than others. Instead what I've done is expose a little syntax sugar that I use to set up the default mappings so that lazy people like you (and me :wink:) don't have to write as much code. Look at this example config:

```Lua
require('neoscroll').setup({
    -- Set whatever options you want
})

local config = require('neoscroll.config')
local t = config.key_to_function
t['<C-u>'] = {'scroll', {'-vim.wo.scroll', 'true', '5'}}
t['<C-d>'] = {'scroll', { 'vim.wo.scroll', 'true', '5'}}
t['<C-b>'] = {'scroll', {'-vim.api.nvim_win_get_height(0)', 'true', '5'}}
t['<C-f>'] = {'scroll', { 'vim.api.nvim_win_get_height(0)', 'true', '5'}}
t['<C-y>'] = {'scroll', {'-0.10', 'false', '10'}}
t['<C-e>'] = {'scroll', { '0.10', 'false', '10'}}
t['zt']    = {'zt', {'5'}}
t['zz']    = {'zz', {'5'}}
t['zb']    = {'zb', {'5'}}

config.set_mappings()
```

You can change any `time_step` as needed (or any other argument) and all the correct mappings (normal, visual and select mode) will be done automatically.

**Comment by kishikaisei** [comment]
Looks good to me, and this solved my need, so thanks and good job 😄
