### ISSUE TITLE
Ease in/out when scrolling

### ISSUE THREAD

**Issue by ouuan** [karb94/neoscroll.nvim#21]
I like the ease in/out feature (fast/abrupt at the beginning, slow at the end) of https://github.com/psliwka/vim-smoothie, while neoscroll supports zt, zz and zb. I'll consider switching to neoscroll if it supports ease in/out.

**Comment by karb94** [comment]
Thank you for your suggestion. I think this would be a welcomed feature. In my head the best way to implement this is to give users the ability to pass their own easing function to the `time_step` argument rather than hard coding a particular function myself (as vim-smoothie does). Of course, I would include example functions in the README.md so that people can copy paste something that works out of the box.

I'll give it a try :)

**Comment by karb94** [comment]
Done in 87a4491. Please, read the [Custom scrolling animations (easing functions)](https://github.com/karb94/neoscroll.nvim#custom-scrolling-animations-easing-functions) section in the README.md and the relevant section in the docs. If something is not clear or you need help let me know.

**Comment by ouuan** [comment]
Is there an easy way to set the same ease function for all commands?

**Comment by karb94** [comment]
There isn't, mainly because you need to also specify the first and last time-step of the scrolling animation as additional arguments and you probably never want to set those to the same value for all the commands as some movements are very long (`c-f`/`c-b`) and some are very short (`c-e`/`c-y`).

I guess I can add some defaults with "easing" enabled  since I already provide a set of defaults anyways but they will be highly opinionated (just as the current ones I guess :smile:).

**Comment by karb94** [comment]
ef74b14 adds two new options: `easing` and `easing_function`. Again, read [Custom scrolling animations (easing functions)](https://github.com/karb94/neoscroll.nvim#custom-scrolling-animations-easing-functions) and the relevant documentation carefully as some breaking changes were needed with respect to the previous commit.

I changed quite a bit of code so I wouldn't be suprised if something broke. Let me know if there are any issues.

**Comment by ouuan** [comment]
I just tried it, but I felt nothing but faster with the easing function. I also tried some strange easing functions such as `function(x) return 0.5 end` and the scroll was not strange but just normal.

**Comment by ouuan** [comment]
BTW, IDK if the information "Scrolling with easing function" was used for debugging, but it's noisy and useless in real use.

**Comment by karb94** [comment]
> I just tried it, but I felt nothing but faster with the easing function. I didn't feel the easing.

If you want to "feel" the easing you'll need to change the default time-step range instead of the easing function. That is what I was trying to explain here:
>There isn't, mainly because you need to also specify the first and last time-step of the scrolling animation as additional arguments and you probably never want to set those to the same value for all the commands as some movements are very long (c-f/c-b) and some are very short (c-e/c-y).

So for instance if you change the `c-d`/`c-u` easing mappings from the README to:
```Lua
t['<C-u>'] = {'scroll', {'-vim.wo.scroll', 'true', '7', '35', easing1}}
t['<C-d>'] = {'scroll', { 'vim.wo.scroll', 'true', '7', '35', easing1}}
```
You'll now "feel" the easing more because it goes from a time-step of 7 ms to a time-step of 35 ms instead of 15 ms. The easing function only determines how the time-step goes from 7 ms to 35 ms. Of course, the higher the value of the last time-step the slower the animation will "feel" towards the end of the scrolling animation. I don't particularly like it that high because you can notice the line-by-line scrolling and it doesn't look as smooth to me but everyone has their own preferences.

So for example with `function(x) return x end` the time-step will decrease from 7 ms to 35 ms linearly whereas with `function(x) return math.pow(x, 2) end` the time-step will decrease from 7 ms to 35 ms quadratically, i.e. slow at the beginning and quickly at the end.

The function `function(x) return 0.5 end` returns a constant so in that case the time-step will be constant throughout the whole scrolling animation. This obviously is totally unnecessary because you don't need an easing function to obtain this scrolling animation.

> BTW, IDK if the information "Scrolling with easing function" was used for debugging, but it's noisy and useless in real use.

You will need to elaborate on what do you mean by "noisy". I am using the defaults and they work just fine for me.

**Comment by ouuan** [comment]
Well, for me it's very hard to understand what "time-step" means without knowing how neoscroll works internally. I didn't find a good explanation in the README. I can only guess what it means. 

It's good to make easing configurable, but I personally prefer the defaults of vim-smoothie to the current defaults of neoscroll.

> You will need to elaborate on what do you mean by "noisy".

![screenshot](https://user-images.githubusercontent.com/30581822/117540914-faaef700-b043-11eb-9c15-37cf6f8ba027.png)

I don't want this line.

**Comment by ouuan** [comment]
Maybe you can provide more presets for the user to choose from. And I'll try playing with the "time-step"s and understand them.

**Comment by ouuan** [comment]
To sum up:

1.  I think it makes more sense to me if "i.e. the time-step between each line scroll is constant" can be changed to "i.e. the time-step (the time duration between two adjacent one-line scrolls) is constant".
2.  I think it's good to provide several presets, and users can contribute their own presets.

**Comment by karb94** [comment]
> Well, for me it's very hard to understand what "time-step" means without knowing how neoscroll works internally. I didn't find a good explanation in the README. I could only guess what it means.

The official documentation of a (neo)vim plugin is always the plugins documentation not the README of the repo. The README is there just for your convenience. If I put everything there it would become very long and no one would read it. Of course it can be improved so your feedback is appreciated. From the docs:
> is the time (in milliseconds) between each single line scroll

All smooth scrolling plugins work in the same way internally. They use `<c-e>`/`<c-y>` to scroll the screen line by line and they leave some time in between each single-line scroll (what I call the time-step).

> I don't want this line below the statusline.

These are some debugging prints that I just removed. Pull the new changes.

**Comment by karb94** [comment]
>I think it makes more sense to me if "i.e. the time-step between each line scroll is constant" can be changed to "i.e. the time-step (the time duration between two adjacent one-line scrolls) is constant".

Agreed. The README and docs need more work. It's always more fun to work on new features than to write good docs :smiley:.

>I think it's good to provide several presets, and users can contribute their own presets.

I don't agree with this. The plugin gives full control over every single animation and that's all it should do. Presets will never please everyone. What will please everyone is having a good enough README that provide examples that can be copy-pasted into their configs and modified according to the users needs. With a good enough README there should be no need for presets. I would allow a "community configs" section in the wiki with a link in the README to it but it will be up to the community to maintain it.

**Comment by ouuan** [comment]
What if the preset is an object in Lua (like the `t` in the example) and can be modified without copy-pasting?

**Comment by ouuan** [comment]
BTW, `:h neoscroll.scroll()` can be added next to `Syntax: t[keys] = {function, {function arguments}}`.

**Comment by karb94** [comment]
I created the wiki if you want to start contributing. I'll add a link to it in the README later.

**Comment by ouuan** [comment]
I realized the biggest reason that I misunderstood the "time-step": it's different from how easing functions work on https://easings.net/ which is listed in the README.

**Comment by karb94** [comment]
Yes I just included the references as examples of how easing functions should look like. The concept is the same but instead of using time as a variable I use the time-step. This makes the coding much easier and the effect should be the same. I'll see if I can make this point clearer in the README.

**Comment by ouuan** [comment]
Is there a site like easings.net that provides easing functions like neoscroll? Users can manually do some math to convert the functions, though.

**Comment by ouuan** [comment]
Now I'm not very comfortable with the scroll in splitter windows. So I think it would be better to have different time-steps for different window sizes, or to set the total time usage in a scroll instead of the time-step per line.

**Comment by ouuan** [comment]
I'd rather like the easing functions on easings.net. Is it very hard to implement? I think we can iterate over each millisecond to calculate how far the cursor should go, and scroll if the cursor hasn't reached where it should be.

**Comment by karb94** [comment]
>Is there a site like easings.net that provides easing functions like neoscroll? Users can manually do some math to convert the functions, though.

You can use any of the functions in easings.net directly in Neoscroll (the example ones are taken from there). The only thing to be aware of is that instead of time Neoscroll uses time-step.

>I'd rather like the easing functions on easings.net. Is it very hard to implement? I think we can iterate over each millisecond to calculate how far the cursor should go, and scroll if the cursor hasn't reached where it should be.

So one (cleaner) solution to the whole time-step thing is to pass how much time do you want the scrolling animation to take. Then the easing functions will map directly. I didn't use this approach because I didn't want to push breaking changes but I think it is for the best. Then you would only need to pass the time and an optional easing function to the `scroll()` function. I'll work on this over the next week probably.

>Now I'm not very comfortable with the scroll in split windows. So I think it would be better to have different time-steps for different window sizes, or to set the total time usage in a scroll instead of the time-step per line.

Yes, so instead of the "time" argument it would be better a "time per line" argument so that this doesn't happen.

Hopefully people don't complain too much after this changes.

**Comment by ouuan** [comment]
> You can use any of the functions in easings.net directly in Neoscroll (the example ones are taken from there). The only thing to be aware of is that instead of time Neoscroll uses time-step.

I don't understand this. As the input and the output are both different, isn't some math calculation needed? Maybe I missed something, can you show me an example how to use a function on easings.net directly?

**Comment by karb94** [comment]
>I don't understand this. As the input and the output are both different, isn't some math calculation needed? Maybe I missed something, can you show me an example how to use a function on easings.net directly?

The easing functions in easings.net (and in pretty much any other place) give you t(x) where t is the **relative** time and x is the **relative** position (i.e., both are defined from 0 to 1). The math is done in the [compute_time_step](https://github.com/karb94/neoscroll.nvim/blob/8f1eba6f3c6e216451eef3d02decca2a47fd2fdd/lua/neoscroll/init.lua#L214) function. To pass a relative position it's easy: number of lines scrolled / number of lines to scroll. Then you get a relative time from 1 to 0. In the case of Neoscroll (and this is what I'm planning to change) the relative time is interpreted as the relative time-step instead, where 0 is the initial time-step and 1 is the final time-step. The maths of this final mapping from relative time-step to real time-step is done in the [last line of the function](https://github.com/karb94/neoscroll.nvim/blob/8f1eba6f3c6e216451eef3d02decca2a47fd2fdd/lua/neoscroll/init.lua#L220) (ignore the `math.floor()` and the `+ 0.5` as these are just there to make sure we get an integer value for the time-step). In this last line `time_step1` is the initial time-step, `time_step2` is the final time-step and `fraction` is the relative time-step obtained from the easing function (t(x)).

**Comment by ouuan** [comment]
Let `t` be the relative time, `x` be the relative position, and `v` be the speed.

The function on easings.net is `x(t)`, but the function of Neoscroll is in proportion to `1/v(x)` while its codomain should be `[0, 1]`. That's what I meant by "math calculation".

For example, `x(t) = t ^ 3` is `v(x) = x ^ (2 / 3)`, so in Neoscroll the function should be something in proportion to `x ^ (-2 / 3)`. But it's hard to map `x ^ (-2 / 3)` to a function whose codomain is `[0, 1]`, because lim `x->0 1/sqrt(x) = ∞`.

**Comment by karb94** [comment]
The functions on easings.net are indeed meant to be used as `x(t)`. I got confused about this because as `f(x)` so my bad.

Either way, I never planned to use them as they are intended to be used with my current implementation because I just wanted a `time_step(x)` that increased the time-step as the position increased and easing functions can fullfill this requirement.

Now, I don't plan to continue with this implementation because it is confusing and the overall approach can be improved. I started working in a new approach in the [time](https://github.com/karb94/neoscroll.nvim/tree/time) branch. In this new approach the user enters the total time of the scrolling animation instead of the time-step(s). This unifies both easing and not easing function arguments but also solves the problem you mentioned here:
>Now I'm not very comfortable with the scroll in split windows. So I think it would be better to have different time-steps for different window sizes, or to set the total time usage in a scroll instead of the time-step per line.

But we still have the issue that ideally we want to have `t(x)` instead of `x(t)` as the easing function because you can then calculate the time-step as `t2(x2) - t1(x1)`. If we have `x(t)` then we need to do something like what you mentioned here:
>I think we can iterate over each millisecond to calculate how far the cursor should go, and scroll if the cursor hasn't reached where it should be.

I would like to avoid iterating over each millisecond as this is just unnecessary overhead which will probably affect performance but it would be nice to just use any easing function that you can find online so if you have any ideas let me know :smiley:. Just to be clear, you can use any easing function you find online at the moment, it's just not going to do exactly what it's supposed to do.

You can play around with the new branch. It's usable.

**Comment by ouuan** [comment]
> Just to be clear, you can use any easing function you find online at the moment, it's just not going to do exactly what it's supposed to do.

Absolutely. But I don't find it useful if they behave differently from what they are supposed to do.

> I would like to avoid iterating over each millisecond as this is just unnecessary overhead which will probably affect performance

I don't know if there's a better approach. Maybe we can require the easing function to be monotonically increasing, in which case we can use binary search.

However, I guess iterating over each millisecond won't notably affect the performance as we only need to do one computation per millisecond.

**Comment by karb94** [comment]
>However, I guess iterating over each millisecond won't notably affect the performance as we only need to do one computation per millisecond.

Maybe not (it's Lua after all) but it's still a very ugly solution. One option is to offer a range of predefined easing functions that are invertible with the corresponding inverse functions hardcoded.

**Comment by karb94** [comment]
In the end I decided to go for the cleaner an more efficient option of hardcoding each easing function individually. Because:
1. Is more convenient for the user as they don't have to code them themselves.
2. The most relevant easing functions are invertible so there is not that much of a downside in the end

I can add additional easing functions upon request.

This came with quite a bit of breaking changes but I think the overall usability of the functions is improved. Read the README and documentation for examples and explanation on how to use the easing functions. If something doesn't work please open a separate issue.
