### ISSUE TITLE
Reverse key press stop scrolling

### ISSUE THREAD

**Issue by jakecastelli** [karb94/neoscroll.nvim#41]
Thanks for the great plugin ❤️ 

I am just wondering if it is possible to stop scrolling by pressing the reverse scrolling key, for example, I am pressing `<C-d>` for scrolling down, and suddenly I want to stop scrolling by pressing `<C-u>`.

I used to use `comfortable-motion.vim`, and it does have this [little piece](https://github.com/psliwka/vim-smoothie/blob/10fd0aa57d176718bc2c570f121ab523c4429a25/autoload/smoothie.vim#L51) I want. 

Cheers,
Jake

**Comment by karb94** [comment]
neoscroll already has this feature. You probably don't notice it because it tries to stop as smoothly as possible instead of immediately stopping. This is because if you have passed an easing function it gives it time to finish the animation smoothly. Try it yourself, press `<c-f>` 4 times and then press `c-u` once. You'll see that it takes way less time to finish the scroll.

Also Neoscroll now tries to detect when you hold down and release your scrolling key and will stop as soon as it detects you released that key. See #38  for details.

**Comment by jakecastelli** [comment]
Thank you heaps!
