### ISSUE TITLE
Incorrect macro playback if it involves `<c-d>` and `<c-u>`

### ISSUE THREAD

**Issue by talbergs** [karb94/neoscroll.nvim#9]
Steps to reproduce:
- start a macro
- append text to line
- `<c-d>`
- append text to line
- `<c-u>`
- Replay macro.

Observed: consequent macros append to a line below, as if `<c-u>` and `<c-d>` actually were `j` and `k`

**Comment by karb94** [comment]
The scrolling command are not instantaneous, it creates a timer that runs until the scrolling finishes. They do have an instantaneous `j`/`k` as the first movement before the timer starts because `vim.loop.new_timer()` doesn't call its callback function until the first time-step has passed. That is why it looks like only `j` or `k` are pressed. Sadly, I don't think there is a way to fix this. Do other smooth-scrolling plugins handle macros properly (to get some inspiration)? Also, in what instances would you use `<C-u>`/`<C-d>` in a macro? Usually macros are for precise actions.

I'll close this issue for now but if anyone has any ideas on how to fix this I'll reopen.

side note: If you press `<C-u>` and later in the macro `<C-d>` you will end up in the same place at the end of the macro because that is what would happen if you rapidly press `<C-u><C-d>`.

**Comment by voyeg3r** [comment]
Why not add an option to disable neoscroll in mappings?

```lua
--@ rturns true or false
M.is_recording = function()
  return vim.fn.reg_recording() ~= nil
end
```

The sbove function could be used to create an option: disable_in_macros (bollean)

if disable_in_macros == true and not is_tecording ...
